export default [
    {
        orderID: 1,
        recepientFirstName: 'John',
        recepientLastName: 'Doe',
        senderFirstName: 'Amanda',
        senderLastName: 'Collins',
        originCountry: 'US',
        originState: 'IL',
        originZipCode: 60610,
        originStreet: '3201 S State St',
        destinationCountry: 'US',
        destinationCity: 'Springs',
        destinationState: 'CO',
        destinationZipCode: 30011,
        destinationStreet: '3501 Clark St'
    },
    {
        orderID: 2,
        recepientFirstName: 'Lucas',
        recepientLastName: 'Spencer',
        senderFirstName: 'Will',
        senderLastName: 'Smith',
        originCountry: 'US',
        originState: 'IL',
        originZipCode: 60610,
        originStreet: '3201 S State St',
        destinationCountry: 'US',
        destinationCity: 'Springs',
        destinationState: 'CO',
        destinationZipCode: 30011,
        destinationStreet: '3501 Clark St'
    },
    {
        orderID: 3,
        recepientFirstName: 'John',
        recepientLastName: 'Doe',
        senderFirstName: 'Amanda',
        senderLastName: 'Collins',
        originCountry: 'US',
        originState: 'IL',
        originZipCode: 60610,
        originStreet: '3201 S State St',
        destinationCity: 'Springs',
        destinationCountry: 'US',
        destinationState: 'CO',
        destinationZipCode: 30011,
        destinationStreet: '3501 Clark St'
    }
];